### ISSUE TITLE
What is this repo?

### ISSUE THREAD

**Issue by vladinator1000** [EmbarkStudios/buildkite-jobify#6]
Hi y'all, I can't understand what this does, can someone explain what it is in simple terms? I've used Buildkite but still can't understand 🙈

I've used Buildkite with cloudformation on AWS, where it would spin up new instances with agents on them according to demand, is this similar but using Kubernetes?

**Comment by Jake-Shadle** [comment]
Yes, that's basically what this does, matches a job request from buildkite to the appropriate container image and spins up the image via kubernetes, then exits the pod once the job is done to clean up the agent.

**Comment by vladinator1000** [comment]
That's lovely, thank you for the reply.
